import Head from "next/head";

const Home = () => (
  <>
    <Head>
      <title>Home</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <main>
      Hello.
      <div>
        <br />- Andrés Aguilera
      </div>
    </main>
  </>
);
export default Home;
