import Head from "next/head";
import ShiftGrid from "@/components/ShiftGrid";

const Shifts = () => {
  return (
    <>
      <Head>
        <title>Shifts</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div style={{ width: "80%", margin: "auto" }}>
          <ShiftGrid />
        </div>
      </main>
    </>
  );
};
export default Shifts;
